### ISSUE TITLE
Environment Setup Issue: Conda command not found error

### ISSUE THREAD

**Issue by Shaleos** [xin-huang/Lithuanian-archaic-introgression#6]
I followed the instruction of the README file and tried to run the workflow on the Life Science Compute Cluster.

Steps Taken:
1. Installed Mambaforge
2. Created environment using `mamba env create -f workflow/envs/env.yaml`
3. Activated environment using `conda activate lai`
4. Attempted to run workflow using `snakemake -c 1 --use-conda --profile config/slurm`

Error Message:
Using profile config/slurm for setting default command line arguments.
Building DAG of jobs...
/usr/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/__init__.py", line 792, in snakemake
    success = workflow.execute(
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/workflow.py", line 1078, in execute
    dag.create_conda_envs(
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/dag.py", line 359, in create_conda_envs
    env.create(dryrun)
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 393, in create
    pin_file = self.pin_file
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/common/__init__.py", line 217, in __get__
    value = self.method(instance)
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 103, in pin_file
    f".{self.conda.platform}.pin.txt"
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/common/__init__.py", line 217, in __get__
    value = self.method(instance)
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 96, in conda
    return Conda(
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 653, in __init__
    shell.check_output(self._get_cmd("conda info --json"), text=True)
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/site-packages/snakemake/shell.py", line 61, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/lisc/user/chen/mambaforge/envs/lai/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.

Additional information:
The activation of the environment appears successful however, if I understand it correctly , the conda command cannot be recognized and 'conda info --json' can't be executed.

**Comment by xin-huang** [comment]
let's check this together tomorrow
